/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TubesRouteImport } from './routes/tubes'
import { Route as ProximityRouteImport } from './routes/proximity'
import { Route as MapRouteImport } from './routes/map'
import { Route as BearingTableRouteImport } from './routes/bearing-table'
import { Route as IndexRouteImport } from './routes/index'

const TubesRoute = TubesRouteImport.update({
  id: '/tubes',
  path: '/tubes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProximityRoute = ProximityRouteImport.update({
  id: '/proximity',
  path: '/proximity',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const BearingTableRoute = BearingTableRouteImport.update({
  id: '/bearing-table',
  path: '/bearing-table',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bearing-table': typeof BearingTableRoute
  '/map': typeof MapRoute
  '/proximity': typeof ProximityRoute
  '/tubes': typeof TubesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bearing-table': typeof BearingTableRoute
  '/map': typeof MapRoute
  '/proximity': typeof ProximityRoute
  '/tubes': typeof TubesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bearing-table': typeof BearingTableRoute
  '/map': typeof MapRoute
  '/proximity': typeof ProximityRoute
  '/tubes': typeof TubesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bearing-table' | '/map' | '/proximity' | '/tubes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bearing-table' | '/map' | '/proximity' | '/tubes'
  id: '__root__' | '/' | '/bearing-table' | '/map' | '/proximity' | '/tubes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BearingTableRoute: typeof BearingTableRoute
  MapRoute: typeof MapRoute
  ProximityRoute: typeof ProximityRoute
  TubesRoute: typeof TubesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tubes': {
      id: '/tubes'
      path: '/tubes'
      fullPath: '/tubes'
      preLoaderRoute: typeof TubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proximity': {
      id: '/proximity'
      path: '/proximity'
      fullPath: '/proximity'
      preLoaderRoute: typeof ProximityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bearing-table': {
      id: '/bearing-table'
      path: '/bearing-table'
      fullPath: '/bearing-table'
      preLoaderRoute: typeof BearingTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BearingTableRoute: BearingTableRoute,
  MapRoute: MapRoute,
  ProximityRoute: ProximityRoute,
  TubesRoute: TubesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
